#注册中心
eureka:
  #      元数据信息
  instance:
    metadata-map:
      dalao: Isteng
  client:
    #设置服务注册中心的URL
    service-url:
      defaultZone: http://euk1.com:7001/eureka/


spring:
  application:
    name: teng_consumer


server:
  port: 8006
