# dashboard 配置  http://localhost:90/actuator/hystrix.stream  http://localhost:90/hystrix/monitor?stream=http%3A%2F%2Flocalhost%3A90%2Factuator%2Fhystrix.stream




logging:
  level:
    root: INFO
    org.springframework.web.servlet.DispatcherServlet: DEBUG
    org.springframework.cloud.sleuth: DEBUG

spring:
  #zipkin
  zipkin:
    base-url: http://localhost:9411/
    #采样比例1
  sleuth:
    sampler:
      rate: 1